// import { OrdenServicio } from "../../class/OrdenServicio";

import { OrdenServicio } from '../../class/OrdenServicio';

export const CORDENES_SERVICIO: OrdenServicio[] = [
  // new OrdenServicio({
  //   id: 232,
  //   precio: 75,
  //   detallePago: [],
  //   idPersonaEnvia: 0,
  //   contactos: [],
  //   recepcion: {
  //     idOrigen: 0,
  //     idTipoRecepcion: 0,
  //     direccionRecepcion: '',
  //   },
  //   entrega: {
  //     idDestino: 0,
  //     idTipoEntrega: 0,
  //     direccionEntrega: '',
  //   },
  //   pagador: {
  //     idCliente: 141,
  //     pagador: 'Remitente',
  //     documento: '73617110',
  //   },
  //   detalleCarga: [],
  //   serviciosAcionales: [],
  //   objetosComunes: [],
  //   observacion: 'Test de Observacion',
  //   detallesAdicionales: '',
  //   documentoSerie: {
  //     tipoDocumentoSerie: {
  //       id: 0,
  //       descripcion: '',
  //       estado: true,
  //     },
  //     serie: '',
  //     detallesAdicionales: '',
  //   },
  //   codigoSeguridad: '',
  //   formaPago: {
  //     id: 3,
  //     descripcion: 'Credito 7 Dias',
  //     estado: true,
  //   },
  //   guiaRemitente: '',
  //   guia: '',
  //   remitente: {
  //     id: 141,
  //     departamento: {
  //       id: 13,
  //       descripcion: 'LA LIBERTAD',
  //       estado: true,
  //     },
  //     provincia: {
  //       id: 1301,
  //       descripcion: 'TRUJILLO',
  //       estado: true,
  //     },
  //     distrito: {
  //       id: 130102,
  //       descripcion: 'EL PORVENIR',
  //       estado: true,
  //     },
  //     tipoDocumento: {
  //       id: 52,
  //       descripcion: 'Doc. Nacional de Identidad',
  //       estado: true,
  //     },
  //     documento: '73617110',
  //     nombre: 'SIDAME HARRY',
  //     apellidos: 'ORE LARA',
  //     nombreCompleto: '',
  //     razonSocial: 'SIDAME HARRY ORE LARA',
  //     ubigeo: '130102',
  //     telefono: '931070632',
  //     correo: 'harry@gmail.com',
  //     contacto: '',
  //     direccion: 'Alto Trujilllo- Barrio 3C- Manzan.C- Lote 45',
  //     activo: false,
  //     credito: false,
  //     contactos: [],
  //     direcciones: [],
  //   },
  //   destinatario: {
  //     id: 143,
  //     departamento: {
  //       id: 0,
  //       descripcion: '',
  //       estado: true,
  //     },
  //     provincia: {
  //       id: 0,
  //       descripcion: '',
  //       estado: true,
  //     },
  //     distrito: {
  //       id: 0,
  //       descripcion: '',
  //       estado: true,
  //     },
  //     tipoDocumento: {
  //       id: 52,
  //       descripcion: 'Doc. Nacional de Identidad',
  //       estado: true,
  //     },
  //     documento: '73617114',
  //     nombre: 'NIXI DENISSE',
  //     apellidos: 'GARCIA RAMOS',
  //     nombreCompleto: '',
  //     razonSocial: 'NIXI DENISSE GARCIA RAMOS',
  //     ubigeo: '',
  //     telefono: '',
  //     correo: '',
  //     contacto: '',
  //     direccion: '',
  //     activo: false,
  //     credito: false,
  //     contactos: [],
  //     direcciones: [],
  //   },
  //   deudaActual: 75,
  //   fecha: new Date('2024-12-26T17:39:28.646Z'),
    
  //   nroGuiaTransportista: '',
  //   origen: 'San Luis',
  //   destino: 'Chimbote',
  //   cantidadBultos: 0,
  //   comprobante: '',
  //   estadoPagado: 1,
  //   metodoPago: {
  //     id: 0,
  //     descripcion: '',
  //     estado: true,
  //   },
  //   fechaPago: new Date('2024-12-26T17:39:28.646Z'),
  //   nroManifiesto: '',
  //   usuario: '',
  // }),
  // new OrdenServicio({
  //   id: 233,
  //   precio: 75,
  //   detallePago: [],
  //   idPersonaEnvia: 0,
  //   contactos: [],
  //   recepcion: {
  //     idOrigen: 0,
  //     idTipoRecepcion: 0,
  //     direccionRecepcion: '',
  //   },
  //   entrega: {
  //     idDestino: 0,
  //     idTipoEntrega: 0,
  //     direccionEntrega: '',
  //   },
  //   pagador: {
  //     idCliente: 141,
  //     pagador: 'Remitente',
  //     documento: '73617110',
  //   },
  //   detalleCarga: [],
  //   serviciosAcionales: [],
  //   objetosComunes: [],
  //   observacion: 'Test de Observacion',
  //   detallesAdicionales: '',
  //   documentoSerie: {
  //     tipoDocumentoSerie: {
  //       id: 0,
  //       descripcion: '',
  //       estado: true,
  //     },
  //     serie: '',
  //     detallesAdicionales: '',
  //   },
  //   codigoSeguridad: '',
  //   formaPago: {
  //     id: 3,
  //     descripcion: 'Credito 7 Dias',
  //     estado: true,
  //   },
  //   guiaRemitente: '',
  //   guia: '',
  //   remitente: {
  //     id: 143,
  //     departamento: {
  //       id: 0,
  //       descripcion: '',
  //       estado: true,
  //     },
  //     provincia: {
  //       id: 0,
  //       descripcion: '',
  //       estado: true,
  //     },
  //     distrito: {
  //       id: 0,
  //       descripcion: '',
  //       estado: true,
  //     },
  //     tipoDocumento: {
  //       id: 52,
  //       descripcion: 'Doc. Nacional de Identidad',
  //       estado: true,
  //     },
  //     documento: '73617114',
  //     nombre: 'NIXI DENISSE',
  //     apellidos: 'GARCIA RAMOS',
  //     nombreCompleto: '',
  //     razonSocial: 'NIXI DENISSE GARCIA RAMOS',
  //     ubigeo: '',
  //     telefono: '',
  //     correo: '',
  //     contacto: '',
  //     direccion: '',
  //     activo: false,
  //     credito: false,
  //     contactos: [],
  //     direcciones: [],
  //   },
  //   destinatario: {
  //     id: 142,
  //     departamento: {
  //       id: 13,
  //       descripcion: 'LA LIBERTAD',
  //       estado: true,
  //     },
  //     provincia: {
  //       id: 1301,
  //       descripcion: 'TRUJILLO',
  //       estado: true,
  //     },
  //     distrito: {
  //       id: 130102,
  //       descripcion: 'EL PORVENIR',
  //       estado: true,
  //     },
  //     tipoDocumento: {
  //       id: 54,
  //       descripcion: 'Registro Único de Contribuyentes',
  //       estado: true,
  //     },
  //     documento: '20612215210',
  //     nombre: '',
  //     apellidos: '',
  //     nombreCompleto: '',
  //     razonSocial: 'ANDESKAR S.A.C.',
  //     ubigeo: '130102',
  //     telefono: '925151511',
  //     correo: '',
  //     contacto: '',
  //     direccion: 'CAL. LAS PONCIANAS NRO 888 URB. LA RINCONADA ',
  //     activo: false,
  //     credito: false,
  //     contactos: [],
  //     direcciones: [],
  //   },
  //   deudaActual: 75,
  //   fecha: new Date('2024-12-26T17:39:28.646Z'),
    
  //   nroGuiaTransportista: '',
  //   origen: 'San Luis',
  //   destino: 'Chimbote',
  //   cantidadBultos: 0,

  //   comprobante: '',
  //   estadoPagado: 1,
  //   metodoPago: {
  //     id: 0,
  //     descripcion: '',
  //     estado: true,
  //   },
  //   fechaPago: new Date('2024-12-26T17:39:28.646Z'),
  //   nroManifiesto: '',
  //   usuario: '',
  // }),
];
