// import { ResponseOrdenServicioDTO } from '../../class/OrdenServicio';

// export const C_RESPONSE_ORDEN_SERVICIO: any[] = [
//   {
//     id: 200,
//     precio: 313,
//     detallePago: [],
//     formaPago: {
//       id: 1,
//       descripcion: 'Contado',
//       createdAt: '0001-01-01T00:00:00',
//     },
//     guiaRemitente: '',
//     guia: '',
//     remitente: {
//       id: 141,
//       documento: '73617110',
//       nombre: 'SIDAME HARRY',
//       apellidos: 'ORE LARA',
//       razonSocial: 'SIDAME HARRY ORE LARA',
//       departamento: 1,
//       direccion: 'Alto Trujilllo- Barrio 3C- Manzan.C- Lote 45',
//       telefono: '931070632',
//       correo: 'harry@gmail.com',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 1,
//       direcciones: [],
//       contactos: [],
//     },
//     destinatario: {
//       id: 142,
//       documento: '20612215210',
//       razonSocial: 'ANDESKAR S.A.C.',
//       departamento: 0,
//       direccion: 'CAL. LAS PONCIANAS NRO 888 URB. LA RINCONADA ',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 2,
//       direcciones: [],
//       contactos: [],
//     },
//     deudaActual: 313,
//     quienPaga: '',
//     fecha: '2024-11-10T00:00:00',
//     nroOrden: 'OS01-00000154',
//     nroGuiaTransportista: '',
//     origen: 'San Luis',
//     destino: 'Chimbote',
//     cantidadBultos: 14,
//     comprobante: '',
//     estadoPagado: 3,
//     metodoPago: {
//       id: 3,
//       descripcion: 'Yape',
//     },
//     fechaPago: '2024-11-10T05:00:00',
//     nroManifiesto: '',
//     usuario: 'Cristhian Chavez 3',
//   },
//   {
//     id: 199,
//     precio: 146,
//     detallePago: [],
//     formaPago: {
//       id: 1,
//       descripcion: 'Contado',
//       createdAt: '0001-01-01T00:00:00',
//     },
//     guiaRemitente: '',
//     guia: '',
//     remitente: {
//       id: 143,
//       documento: '73617114',
//       nombre: 'NIXI DENISSE',
//       apellidos: 'GARCIA RAMOS',
//       razonSocial: 'NIXI DENISSE GARCIA RAMOS',
//       departamento: 0,
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 1,
//       direcciones: [],
//       contactos: [],
//     },
//     destinatario: {
//       id: 155,
//       documento: '20131372184',
//       razonSocial: 'MUNICIPALIDAD DISTRITAL DE SAN MIGUEL',
//       departamento: 0,
//       direccion: 'JR. FEDERICO GALLESE TARICCHI NRO 370 URB. SAN MIGUEL ',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 2,
//       direcciones: [],
//       contactos: [],
//     },
//     deudaActual: 146,
//     quienPaga: '',
//     fecha: '2024-11-10T00:00:00',
//     nroOrden: 'OS01-00000153',
//     nroGuiaTransportista: '',
//     origen: 'Piura',
//     destino: 'San Luis',
//     cantidadBultos: 6,
//     comprobante: '',
//     estadoPagado: 3,
//     metodoPago: {
//       id: 2,
//       descripcion: 'Tarjeta Credito o Debito visa',
//     },
//     fechaPago: '2024-11-10T05:00:00',
//     nroManifiesto: '',
//     usuario: 'Cristhian Chavez 3',
//   },
//   {
//     id: 198,
//     precio: 84,
//     detallePago: [],
//     formaPago: {
//       id: 1,
//       descripcion: 'Contado',
//       createdAt: '0001-01-01T00:00:00',
//     },
//     guiaRemitente: '',
//     guia: '',
//     remitente: {
//       id: 140,
//       documento: '43425643',
//       nombre: 'JUAN JOSE',
//       apellidos: 'ORE LESCANO',
//       razonSocial: 'JUAN JOSE ORE LESCANO',
//       departamento: 0,
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 1,
//       direcciones: [],
//       contactos: [],
//     },
//     destinatario: {
//       id: 154,
//       documento: '20103365628',
//       razonSocial: 'DISTRIBUCIONES OLANO S.A.C.',
//       departamento: 0,
//       direccion: 'CAL. LEONCIO PRADO NRO 549 URB. EL PORVENIR ',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 2,
//       direcciones: [],
//       contactos: [],
//     },
//     deudaActual: 84,
//     quienPaga: '',
//     fecha: '2024-11-10T00:00:00',
//     nroOrden: 'OS01-00000152',
//     nroGuiaTransportista: '',
//     origen: 'Trujillo',
//     destino: 'San Luis',
//     cantidadBultos: 4,
//     comprobante: '',
//     estadoPagado: 3,
//     metodoPago: {
//       id: 3,
//       descripcion: 'Yape',
//     },
//     fechaPago: '2024-11-10T05:00:00',
//     nroManifiesto: '',
//     usuario: 'Cristhian Chavez 3',
//   },
//   {
//     id: 197,
//     precio: 99,
//     detallePago: [],
//     formaPago: {
//       id: 1,
//       descripcion: 'Contado',
//       createdAt: '0001-01-01T00:00:00',
//     },
//     guiaRemitente: '',
//     guia: '',
//     remitente: {
//       id: 141,
//       documento: '73617110',
//       nombre: 'SIDAME HARRY',
//       apellidos: 'ORE LARA',
//       razonSocial: 'SIDAME HARRY ORE LARA',
//       departamento: 1,
//       direccion: 'Alto Trujilllo- Barrio 3C- Manzan.C- Lote 45',
//       telefono: '931070632',
//       correo: 'harry@gmail.com',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 1,
//       direcciones: [],
//       contactos: [],
//     },
//     destinatario: {
//       id: 142,
//       documento: '20612215210',
//       razonSocial: 'ANDESKAR S.A.C.',
//       departamento: 0,
//       direccion: 'CAL. LAS PONCIANAS NRO 888 URB. LA RINCONADA ',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 2,
//       direcciones: [],
//       contactos: [],
//     },
//     deudaActual: 99,
//     quienPaga: '',
//     fecha: '2024-11-10T00:00:00',
//     nroOrden: 'OS01-00000151',
//     nroGuiaTransportista: '',
//     origen: 'San Luis',
//     destino: 'Trujillo',
//     cantidadBultos: 2,
//     comprobante: '',
//     estadoPagado: 3,
//     metodoPago: {
//       id: 3,
//       descripcion: 'Yape',
//     },
//     fechaPago: '2024-11-12T05:00:00',
//     nroManifiesto: '',
//     usuario: 'Cristhian Chavez 3',
//   },
//   {
//     id: 196,
//     precio: 45,
//     detallePago: [],
//     formaPago: {
//       id: 1,
//       descripcion: 'Contado',
//       createdAt: '0001-01-01T00:00:00',
//     },
//     guiaRemitente: '',
//     guia: '',
//     remitente: {
//       id: 141,
//       documento: '73617110',
//       nombre: 'SIDAME HARRY',
//       apellidos: 'ORE LARA',
//       razonSocial: 'SIDAME HARRY ORE LARA',
//       departamento: 1,
//       direccion: 'Alto Trujilllo- Barrio 3C- Manzan.C- Lote 45',
//       telefono: '931070632',
//       correo: 'harry@gmail.com',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 1,
//       direcciones: [],
//       contactos: [],
//     },
//     destinatario: {
//       id: 142,
//       documento: '20612215210',
//       razonSocial: 'ANDESKAR S.A.C.',
//       departamento: 0,
//       direccion: 'CAL. LAS PONCIANAS NRO 888 URB. LA RINCONADA ',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 2,
//       direcciones: [],
//       contactos: [],
//     },
//     deudaActual: 45,
//     quienPaga: '',
//     fecha: '2024-11-10T00:00:00',
//     nroOrden: 'OS01-00000150',
//     nroGuiaTransportista: '',
//     origen: 'San Luis',
//     destino: 'Chimbote',
//     cantidadBultos: 2,
//     comprobante: '',
//     estadoPagado: 3,
//     metodoPago: {
//       id: 2,
//       descripcion: 'Tarjeta Credito o Debito visa',
//     },
//     fechaPago: '2024-11-10T05:00:00',
//     nroManifiesto: '',
//     usuario: 'Cristhian Chavez 3',
//   },
//   {
//     id: 195,
//     precio: 97.5,
//     detallePago: [],
//     formaPago: {
//       id: 1,
//       descripcion: 'Contado',
//       createdAt: '0001-01-01T00:00:00',
//     },
//     guiaRemitente: '',
//     guia: '',
//     remitente: {
//       id: 141,
//       documento: '73617110',
//       nombre: 'SIDAME HARRY',
//       apellidos: 'ORE LARA',
//       razonSocial: 'SIDAME HARRY ORE LARA',
//       departamento: 1,
//       direccion: 'Alto Trujilllo- Barrio 3C- Manzan.C- Lote 45',
//       telefono: '931070632',
//       correo: 'harry@gmail.com',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 1,
//       direcciones: [],
//       contactos: [],
//     },
//     destinatario: {
//       id: 153,
//       documento: '20608331604',
//       razonSocial: 'SISTEMA DALAS GLOBAL S.A.C.',
//       departamento: 0,
//       direccion: 'AV. HUANDOY MZA. K LOTE 25 URB. SAN ELIAS ',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 2,
//       direcciones: [],
//       contactos: [],
//     },
//     deudaActual: 97.5,
//     quienPaga: '',
//     fecha: '2024-11-10T00:00:00',
//     nroOrden: 'OS01-00000149',
//     nroGuiaTransportista: '',
//     origen: 'Chiclayo',
//     destino: 'Trujillo',
//     cantidadBultos: 7,
//     comprobante: '',
//     estadoPagado: 2,
//     metodoPago: {
//       id: 4,
//       descripcion: 'Plin',
//     },
//     fechaPago: '2024-11-10T05:00:00',
//     nroManifiesto: '',
//     usuario: 'Cristhian Chavez 3',
//   },
//   {
//     id: 194,
//     precio: 112,
//     detallePago: [],
//     formaPago: {
//       id: 1,
//       descripcion: 'Contado',
//       createdAt: '0001-01-01T00:00:00',
//     },
//     guiaRemitente: '',
//     guia: '',
//     remitente: {
//       id: 141,
//       documento: '73617110',
//       nombre: 'SIDAME HARRY',
//       apellidos: 'ORE LARA',
//       razonSocial: 'SIDAME HARRY ORE LARA',
//       departamento: 1,
//       direccion: 'Alto Trujilllo- Barrio 3C- Manzan.C- Lote 45',
//       telefono: '931070632',
//       correo: 'harry@gmail.com',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 1,
//       direcciones: [],
//       contactos: [],
//     },
//     destinatario: {
//       id: 142,
//       documento: '20612215210',
//       razonSocial: 'ANDESKAR S.A.C.',
//       departamento: 0,
//       direccion: 'CAL. LAS PONCIANAS NRO 888 URB. LA RINCONADA ',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 2,
//       direcciones: [],
//       contactos: [],
//     },
//     deudaActual: 112,
//     quienPaga: '',
//     fecha: '2024-11-10T00:00:00',
//     nroOrden: 'OS01-00000148',
//     nroGuiaTransportista: '',
//     origen: 'Huamachuco',
//     destino: 'Trujillo',
//     cantidadBultos: 5,
//     comprobante: '',
//     estadoPagado: 3,
//     metodoPago: {
//       id: 2,
//       descripcion: 'Tarjeta Credito o Debito visa',
//     },
//     fechaPago: '2024-11-10T05:00:00',
//     nroManifiesto: '',
//     usuario: 'Cristhian Chavez 3',
//   },
//   {
//     id: 193,
//     precio: 145,
//     detallePago: [],
//     formaPago: {
//       id: 1,
//       descripcion: 'Contado',
//       createdAt: '0001-01-01T00:00:00',
//     },
//     guiaRemitente: '',
//     guia: '',
//     remitente: {
//       id: 141,
//       documento: '73617110',
//       nombre: 'SIDAME HARRY',
//       apellidos: 'ORE LARA',
//       razonSocial: 'SIDAME HARRY ORE LARA',
//       departamento: 1,
//       direccion: 'Alto Trujilllo- Barrio 3C- Manzan.C- Lote 45',
//       telefono: '931070632',
//       correo: 'harry@gmail.com',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 1,
//       direcciones: [],
//       contactos: [],
//     },
//     destinatario: {
//       id: 152,
//       documento: '20606716797',
//       razonSocial: 'GRUPO ITSACORP S.A.C.',
//       departamento: 0,
//       direccion: 'AV. FLORA TRISTAN NRO 617 DEP. 302 ',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 2,
//       direcciones: [],
//       contactos: [],
//     },
//     deudaActual: 145,
//     quienPaga: '',
//     fecha: '2024-11-10T00:00:00',
//     nroOrden: 'OS01-00000147',
//     nroGuiaTransportista: '',
//     origen: 'Trujillo',
//     destino: 'Huamachuco',
//     cantidadBultos: 6,
//     comprobante: '',
//     estadoPagado: 3,
//     metodoPago: {
//       id: 2,
//       descripcion: 'Tarjeta Credito o Debito visa',
//     },
//     fechaPago: '2024-11-06T05:00:00',
//     nroManifiesto: '',
//     usuario: 'Cristhian Chavez 3',
//   },
//   {
//     id: 192,
//     precio: 105,
//     detallePago: [],
//     formaPago: {
//       id: 1,
//       descripcion: 'Contado',
//       createdAt: '0001-01-01T00:00:00',
//     },
//     guiaRemitente: '',
//     guia: '',
//     remitente: {
//       id: 140,
//       documento: '43425643',
//       nombre: 'JUAN JOSE',
//       apellidos: 'ORE LESCANO',
//       razonSocial: 'JUAN JOSE ORE LESCANO',
//       departamento: 0,
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 1,
//       direcciones: [],
//       contactos: [],
//     },
//     destinatario: {
//       id: 145,
//       documento: '20133605291',
//       razonSocial: 'EMPRESA DE TRANSPORTES AVE FENIX S.A.C.',
//       departamento: 0,
//       direccion: 'AV. TUPAC AMARU NRO 185 URB. HUERTA GRANDE ',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 2,
//       direcciones: [],
//       contactos: [],
//     },
//     deudaActual: 105,
//     quienPaga: '',
//     fecha: '2024-11-10T00:00:00',
//     nroOrden: 'OS01-00000146',
//     nroGuiaTransportista: '',
//     origen: 'Chimbote',
//     destino: 'Sullana',
//     cantidadBultos: 3,
//     comprobante: '',
//     estadoPagado: 3,
//     metodoPago: {
//       id: 4,
//       descripcion: 'Plin',
//     },
//     fechaPago: '2024-11-08T05:00:00',
//     nroManifiesto: '',
//     usuario: 'Cristhian Chavez 3',
//   },
//   {
//     id: 191,
//     precio: 20,
//     detallePago: [],
//     formaPago: {
//       id: 1,
//       descripcion: 'Contado',
//       createdAt: '0001-01-01T00:00:00',
//     },
//     guiaRemitente: '',
//     guia: '',
//     remitente: {
//       id: 141,
//       documento: '73617110',
//       nombre: 'SIDAME HARRY',
//       apellidos: 'ORE LARA',
//       razonSocial: 'SIDAME HARRY ORE LARA',
//       departamento: 1,
//       direccion: 'Alto Trujilllo- Barrio 3C- Manzan.C- Lote 45',
//       telefono: '931070632',
//       correo: 'harry@gmail.com',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 1,
//       direcciones: [],
//       contactos: [],
//     },
//     destinatario: {
//       id: 142,
//       documento: '20612215210',
//       razonSocial: 'ANDESKAR S.A.C.',
//       departamento: 0,
//       direccion: 'CAL. LAS PONCIANAS NRO 888 URB. LA RINCONADA ',
//       oficina: 0,
//       credito: false,
//       tipoDocumento: 2,
//       direcciones: [],
//       contactos: [],
//     },
//     deudaActual: 20,
//     quienPaga: '',
//     fecha: '2024-11-10T00:00:00',
//     nroOrden: 'OS01-00000145',
//     nroGuiaTransportista: '',
//     origen: 'San Luis',
//     destino: 'Chiclayo',
//     cantidadBultos: 1,
//     comprobante: '',
//     estadoPagado: 3,
//     metodoPago: {
//       id: 2,
//       descripcion: 'Tarjeta Credito o Debito visa',
//     },
//     fechaPago: '2024-11-05T05:00:00',
//     nroManifiesto: '',
//     usuario: 'Cristhian Chavez 3',
//   },
// ];
