import { ActivosState, TrayectoriaState } from 'src/app/shared/enums';
import { Trayectoria } from '../../class/operaciones/trayectoria/Trayectoria.class';

export const C_TRAYECTORIA: Trayectoria[] = [
  new Trayectoria({
    id: 1,
    origen: {
      id: 101,
      idTrayectoria: 1001,
      nombre: 'Agencia Central',
      horarioInicio: '08:00',
      horarioTermino: '18:00',
      deparamento:{
        id: 1,
        descripcion: 'Lima',
        estado: true,
      },
      direccion: 'Av. Principal 123',
      activo: true,
      viaje: '02:00',
      estiba: '00:30',
      orden: 1,
      trayectoriaTipo: TrayectoriaState.INICIAL,
    },
    destino: {
      id: 102,
      idTrayectoria: 1002,
      nombre: 'Agencia Norte',
      horarioInicio: '09:00',
      horarioTermino: '19:00',
      direccion: 'Calle Secundaria 456',
      deparamento:{
        id: 2,
        descripcion: 'Arequipa',
        estado: true,
      },
      activo: true,
      viaje: '03:00',
      estiba: '00:45',
      orden: 2,
      trayectoriaTipo: TrayectoriaState.FINAL,
    },
    nombre: 'Ruta Principal',
    // fecha: '2025-01-05',
    estado: ActivosState.ACTIVO,
    agenciasSeleccionadas: [
      {
        id: 103,
        idTrayectoria: 1003,
        nombre: 'Agencia Sur',
        horarioInicio: '07:30',
        horarioTermino: '17:30',
        direccion: 'Jr. Tercero 789',
        deparamento:{
          id: 3,
          descripcion: 'Cusco',
          estado: true,
        },
        activo: true,
        viaje: '01:30',
        estiba: '00:20',
        orden: 3,
        trayectoriaTipo: TrayectoriaState.INTERMEDIO,
      },
    ],
    totalOficinas: 3,
    totalTiempoAcumulado: 360,
  }),
];

const tda = {
  id: 1,
  origen: {
    id: 101,
    idTrayectoria: 1001,
    nombre: 'Agencia Central',
    direccion: 'Av. Principal 123',
    viaje: '02:00',
    estiba: '00:30',
    orden: 1,
    trayectoriaTipo: 1,
  },
  destino: {
    id: 102,
    idTrayectoria: 1002,
    nombre: 'Agencia Norte',
    direccion: 'Calle Secundaria 456',
    viaje: '03:00',
    estiba: '00:45',
    orden: 2,
    trayectoriaTipo: 3,
  },
  nombre: 'Ruta Principal',
  estado: 1,
  agenciasSeleccionadas: [
    {
      id: 101,
      idTrayectoria: 1001,
      nombre: 'Agencia Central',
      direccion: 'Av. Principal 123',
      viaje: '02:00',
      estiba: '00:30',
      orden: 1,
      trayectoriaTipo: 1,
    },
    {
      id: 103,
      idTrayectoria: 1003,
      nombre: 'Agencia Sur',
      direccion: 'Jr. Tercero 789',
      viaje: '01:30',
      estiba: '00:20',
      orden: 3,
      trayectoriaTipo: 2,
    },
    {
      id: 102,
      idTrayectoria: 1002,
      nombre: 'Agencia Norte',
      direccion: 'Calle Secundaria 456',
      viaje: '03:00',
      estiba: '00:45',
      orden: 2,
      trayectoriaTipo: 3,
    },
  ],
};
